language: ruby
before_script: bundle exec rake db:schema:load
rvm:
  - 1.9.3
  - 1.9.2
  - jruby-18mode # JRuby in 1.8 mode
  - jruby-19mode # JRuby in 1.9 mode
  - rbx-18mode
  - rbx-19mode
# uncomment this line if your project needs to run something other than `rake`:
script: bundle exec rspec
