language: ruby
bundler_args: --without development
before_script: bundle exec rake db:schema:load
rvm:
  - 1.9.3
  - 1.9.2
  - 1.8.7
# uncomment this line if your project needs to run something other than `rake`:
script: bundle exec rspec
